# Generated by Django 6.0 on 2025-12-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Заблокирован'), ('active', 'Активен'), ('completed', 'Завершен')], default='locked', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Прогресс урока',
                'verbose_name_plural': 'Прогресс уроков',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Подписка на курс',
                'verbose_name_plural': 'Подписки на курсы',
            },
        ),
    ]
